services:
  db:
    container_name: patima-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: patima
    ports:
      - "3306:3306"
    volumes:
      - patima-db-data:/var/lib/mysql
  #      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build:
      context: django-app
      dockerfile: Dockerfile
    container_name: patima-backend
    command: sh -c "gunicorn patima.wsgi --bind 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - ./django-app:/app
      - ./static:/app/static
    #    ports:
    #        - "8000:8000"
    env_file:
      - ./django-app/.env
    depends_on:
      - db

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: admin-nginx
    volumes:
      - ./admin-panel/nginx.conf:/etc/nginx/nginx.conf
      - ./admin-panel/conf.d:/etc/nginx/conf.d
      - ./admin-panel/angular/browser:/usr/share/nginx/html
      - ./static:/app/static

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: main-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/app/static
    depends_on:
      - admin-panel
      - backend

volumes:
  patima-db-data: